---
version: "{build}-{branch}"

image: Ubuntu2204

branches:
  only:
    - master
    - development

environment:
  fast_finish: true
  APPVEYOR_YML_DISABLE_PS_LINUX: true

platform:
  - x64

configuration:
  - release

install:
  - echo "--- Installing dependencies ---"
  - sudo apt-get --assume-yes update
  - sudo apt-get --assume-yes install cmake

build: off

build_script:
  - echo --- Building ---
  - make -j release
  - echo --- done ---

test: off
